name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/gemy2.jpg
    - assets/images/image3.jpg
    - assets/images/image4.jpg
    - assets/images/image1.jpg
    - assets/images/image2.jpg
    - assets/images/logo.jpg